language: python
python: 3.6
env:
  matrix:
  - build=dev
  - secure: LypuJJ8NVltSGSlSY6/NWEDDP+VrU2J/T8Rwq5w9dfQKCWIi+NAzS59FXHmPqq0xLcOyoX+9MUrnfbg9yL1E/50ahPqmjR4O5Refno54kegqQBa8KudFA0rueOPAhYXkY8z3bczr1QTo3XvgyG1HRx2ENRpTlfL9eepmmB9Miu7Z1xR8nkxBPYrpomdqebumptgN277/50Tkc9G8NHHq1QuFdN7GOFJ9XjK/ofRzEFRtebMB30iBiMS8+KgbTXHzXix9hVyOpqZ5v3eafrz6G5cdb5goMJZqAuYbA7HCjQk79SQYSdftYyFzPSEa9BP06/bcGQjUBD+REYn2YrAJ78cD+hC5SYL/jKHuH02p9PqhUHLBF6smSUxAXfVlffoOcSzWymxysfC8itREjYgtEe3/5QDroCvnQWBO3a4fYR/PDwtkLji9UfcLcpeTvbQJ85ms6TMeL+ROe71+/PsMjNWCPlMCE3RxzlcfOya41WSUYboWTz3UQAH0+575XzctqPlzhcDYsR2w9f3/Hsp2AfYoVsqWqw0i4lzMFXuRGR4U0k3oQNQL7yB73JtfFdJD/SWFm7LhnAU3soGLncdqrFYcNz5mxgsb3AiPSTPjPjtFwiu16D6W7OXTvisSmxqltnaSp9Ss2DIY+Q21Tr0sGcqoHiRHOcxLgEkYPOzqnNc=
script: python3 plot.py || python plot.py
